version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run:
          name: Test
          command: |
            cd exercises
            npm install
            npm test

  lint:
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - run:
          name: Lint 
          command: |
            cd exercises
            npm install
            eslint exercises.js
            
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
      - lint
